# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: libertarian-core-os
description: Sovereign Digital Fortress - Gaming, AI, HTPC and Anti-Orwellian Tools.

base-image: ghcr.io/ublue-os/bazzite
image-version: 40

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      # --- Core Sovereign & Security ---
      - fish
      - mullvad-vpn
      - keepassxc
      - syncthing
      - bleachbit
      - firewalld
      - openssl
      # --- Virtualisation (Pour Whonix/Windows VM) ---
      - virt-manager
      - libvirt
      - qemu-kvm
      # --- System & Drivers ---
      - lshw
      - htop
      - mesa-va-drivers-freeworld
      - waydroid
      - podman-compose

  - type: flatpak
    install:
      # --- Privacy & Anti-Surveillance ---
      - com.brave.Browser
      - io.gitlab.librewolf-community
      - org.torproject.torbrowser-launcher
      - io.simplex.simplex
      - com.github.tchx84.Flatseal
      - com.belmoussaoui.Authenticator
      # --- Workstation & Productivité ---
      - org.onlyoffice.desktopeditors
      - net.cozic.joplin_desktop
      - org.localsend.localsend_app
      - net.ankiweb.Anki
      - io.github.antimatter15.ConverterNow
      - org.gnome.Thunderbird
      - com.visualstudio.code.oss
      # --- Gaming Hub ---
      - com.usebottles.bottles
      - com.heroicgameslauncher.hgl
      - com.github.Matoking.protontricks
      - net.lutris.Lutris
      # --- Multimédia & Souveraineté HTPC ---
      - tv.kodi.Kodi                  # Le roi du HTPC / Media Center local
      - org.videolan.VLC
      - io.bassi.Amberol
      - org.nickvision.tubeconverter
      - io.gitlab.news_flash.NewsFlash

  - type: script
    scripts:
      - post-install.sh
